### ISSUE TITLE
Beta testing issues - pre version 4.0.0 release.

### ISSUE THREAD

**Issue by asudbury** [asudbury/NinjaCoderForMvvmCross#206]
I thought I would create a new thread for issues.

**Comment by lothrop** [comment]
My first try hasn't been so successful:

```
28.02.2016 13:27:15 - Microsoft VSIX Installer
28.02.2016 13:27:15 - -------------------------------------------
28.02.2016 13:27:15 - Initializing Install...
28.02.2016 13:27:15 - Extension Details...
28.02.2016 13:27:15 - 	Identifier         : NinjaCoderMvvmCross.vsix..51ede486-dd91-4fa8-936e-9260508e97cd
28.02.2016 13:27:15 - 	Name               : Ninja Coder For MvvmCross and Xamarin Forms
28.02.2016 13:27:15 - 	Author             : Scorchio Limited
28.02.2016 13:27:15 - 	Version            : 3.9.1
28.02.2016 13:27:15 - 	Description        : Ninja Coder for MvvmCross and Xamarin Forms
28.02.2016 13:27:15 - 	Locale             : en-US
28.02.2016 13:27:15 - 	MoreInfoURL        : 
28.02.2016 13:27:15 - 	InstalledByMSI     : False
28.02.2016 13:27:15 - 	SupportedFrameworkVersionRange : [4.5,)
28.02.2016 13:27:15 - 
28.02.2016 13:27:15 - 	SignatureState     : Unsigned
28.02.2016 13:27:15 - 	Supported Products : 
28.02.2016 13:27:15 - 		Microsoft.VisualStudio.Ultimate
28.02.2016 13:27:15 - 			Version : [14.0]
28.02.2016 13:27:15 - 		Microsoft.VisualStudio.Pro
28.02.2016 13:27:15 - 			Version : [14.0]
28.02.2016 13:27:15 - 		Microsoft.VisualStudio.Premium
28.02.2016 13:27:15 - 			Version : [14.0]
28.02.2016 13:27:15 - 		Microsoft.VisualStudio.Community
28.02.2016 13:27:15 - 			Version : [14.0]
28.02.2016 13:27:15 - 
28.02.2016 13:27:15 - 	References         : 
28.02.2016 13:27:15 - Signature Details...
28.02.2016 13:27:15 - 	Extension is not signed.
28.02.2016 13:27:15 - 
28.02.2016 13:27:15 - Searching for applicable products...
28.02.2016 13:27:16 - Found installed product - Microsoft Visual Studio Professional 2015
28.02.2016 13:27:16 - Found installed product - Microsoft Visual Studio Community 2015
28.02.2016 13:27:16 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
28.02.2016 13:27:16 - Found installed product - Global Location
28.02.2016 13:27:16 - Found installed product - ssms
28.02.2016 13:27:16 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by asudbury** [comment]
@lothrop  hat version of Visual Studio you using?

These are the current version - supported - is yours missing?
        <InstallationTarget Id="Microsoft.VisualStudio.Ultimate" Version="[14.0]" />
        <InstallationTarget Version="[14.0)" Id="Microsoft.VisualStudio.Pro" />
        <InstallationTarget Version="[14.0)" Id="Microsoft.VisualStudio.Premium" />
        <InstallationTarget Version="[14.0)" Id="Microsoft.VisualStudio.Community" />

**Comment by lothrop** [comment]
Well, it does say that it found my installation of Visual Studio Professional 2015 in the logs. Strange.

**Comment by lothrop** [comment]
```
Microsoft Visual Studio Professional 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-40000-00000-AA763
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-40000-00000-AA763
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA763
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA763
Microsoft Visual C++ 2015

Visual F# 2015   00322-40000-00000-AA763
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-40000-00000-AA763
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   4.2.60128.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET and Web Tools 2015 (RC1 Update 1)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.2   14.0.20201.0
Azure App Service Tools v2.8.2

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DataFactoryProject   1.0
Microsoft Data Factory Package

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 2015.1.3   Build 102.0.20150724.141603
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Data Factory Node Node   1.0
Azure Data Factory extension for Visual Studio Server Explorer.

Microsoft Azure HDInsight HQL Service   2.0.2900.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2900.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40114.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   3.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

TypeScript   1.7.6.0
TypeScript for Microsoft Visual Studio

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual C++ for Cross Platform Mobile Development   1.0
Visual C++ for Cross Platform Mobile Development

Visual Studio Tools for Universal Windows Apps   14.0.24720.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.0.1.96 (dcea9c1)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Inspector Support   0.3.2.3 (1b526e6)
Adds support for inspecting Xamarin and WPF apps.

Xamarin.Android   6.0.1.10 (e98e962)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.4.1.24 (47eb74b)
Visual Studio extension to enable development for Xamarin.iOS.
```

**Comment by asudbury** [comment]
The actual plugin is built with VS2013! - do you have that still installed?

**Comment by asudbury** [comment]
ok im going to change the installer 

From 

<Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="4.5" />
To

<Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" MinVersion="4.5" />

Give me a few moments to rebuild

**Comment by asudbury** [comment]
Version 3.9.2 just uploaded - same location

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderMvvmCross.vsix.vsix

**Comment by lothrop** [comment]
@asudbury No, I never installed VS 2013 on this machine. Is the new version not aimed at VS 2015? Or do I just need VS 2013 for the installer? I still get the same message with the new installer.

```
28.02.2016 17:32:39 - Microsoft VSIX Installer
28.02.2016 17:32:39 - -------------------------------------------
28.02.2016 17:32:39 - Initializing Install...
28.02.2016 17:32:39 - Extension Details...
28.02.2016 17:32:39 - 	Identifier         : NinjaCoderMvvmCross.vsix..51ede486-dd91-4fa8-936e-9260508e97cd
28.02.2016 17:32:39 - 	Name               : Ninja Coder For MvvmCross and Xamarin Forms
28.02.2016 17:32:39 - 	Author             : Scorchio Limited
28.02.2016 17:32:39 - 	Version            : 3.9.2
28.02.2016 17:32:39 - 	Description        : Ninja Coder for MvvmCross and Xamarin Forms
28.02.2016 17:32:39 - 	Locale             : en-US
28.02.2016 17:32:39 - 	MoreInfoURL        : 
28.02.2016 17:32:39 - 	InstalledByMSI     : False
28.02.2016 17:32:39 - 	SupportedFrameworkVersionRange : 
28.02.2016 17:32:39 - 
28.02.2016 17:32:39 - 	SignatureState     : Unsigned
28.02.2016 17:32:39 - 	Supported Products : 
28.02.2016 17:32:39 - 		Microsoft.VisualStudio.Ultimate
28.02.2016 17:32:39 - 			Version : [14.0]
28.02.2016 17:32:39 - 		Microsoft.VisualStudio.Pro
28.02.2016 17:32:39 - 			Version : [14.0]
28.02.2016 17:32:39 - 		Microsoft.VisualStudio.Premium
28.02.2016 17:32:39 - 			Version : [14.0]
28.02.2016 17:32:39 - 		Microsoft.VisualStudio.Community
28.02.2016 17:32:39 - 			Version : [14.0]
28.02.2016 17:32:39 - 
28.02.2016 17:32:39 - 	References         : 
28.02.2016 17:32:39 - Signature Details...
28.02.2016 17:32:39 - 	Extension is not signed.
28.02.2016 17:32:39 - 
28.02.2016 17:32:39 - Searching for applicable products...
28.02.2016 17:32:40 - Found installed product - Microsoft Visual Studio Professional 2015
28.02.2016 17:32:40 - Found installed product - Microsoft Visual Studio Community 2015
28.02.2016 17:32:40 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
28.02.2016 17:32:40 - Found installed product - Global Location
28.02.2016 17:32:40 - Found installed product - ssms
28.02.2016 17:32:40 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by asudbury** [comment]
@lothrop you shouldnt need vs2013 installed - if its thats the requirement of the installer then i have done something wrong :-(

I have take out the dependency on any framework in the installer :-)

link to version 3.9.3 below download below

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderMvvmCross.vsix.vsix

if this doesnt work - then i will have to rebuild everything with vs2015 and see if that work - but that will take me some time :-(

**Comment by lothrop** [comment]
Still no luck. 😕

```
28.02.2016 17:52:11 - Microsoft VSIX Installer
28.02.2016 17:52:11 - -------------------------------------------
28.02.2016 17:52:11 - Initializing Install...
28.02.2016 17:52:11 - Extension Details...
28.02.2016 17:52:11 - 	Identifier         : NinjaCoderMvvmCross.vsix..51ede486-dd91-4fa8-936e-9260508e97cd
28.02.2016 17:52:11 - 	Name               : Ninja Coder For MvvmCross and Xamarin Forms
28.02.2016 17:52:11 - 	Author             : Scorchio Limited
28.02.2016 17:52:11 - 	Version            : 3.9.3
28.02.2016 17:52:11 - 	Description        : Ninja Coder for MvvmCross and Xamarin Forms
28.02.2016 17:52:11 - 	Locale             : en-US
28.02.2016 17:52:11 - 	MoreInfoURL        : 
28.02.2016 17:52:11 - 	InstalledByMSI     : False
28.02.2016 17:52:11 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
28.02.2016 17:52:11 - 
28.02.2016 17:52:11 - 	SignatureState     : Unsigned
28.02.2016 17:52:11 - 	Supported Products : 
28.02.2016 17:52:11 - 		Microsoft.VisualStudio.Ultimate
28.02.2016 17:52:11 - 			Version : [14.0]
28.02.2016 17:52:11 - 		Microsoft.VisualStudio.Pro
28.02.2016 17:52:11 - 			Version : [14.0]
28.02.2016 17:52:11 - 		Microsoft.VisualStudio.Premium
28.02.2016 17:52:11 - 			Version : [14.0]
28.02.2016 17:52:11 - 		Microsoft.VisualStudio.Community
28.02.2016 17:52:11 - 			Version : [14.0]
28.02.2016 17:52:11 - 
28.02.2016 17:52:11 - 	References         : 
28.02.2016 17:52:11 - Signature Details...
28.02.2016 17:52:11 - 	Extension is not signed.
28.02.2016 17:52:11 - 
28.02.2016 17:52:11 - Searching for applicable products...
28.02.2016 17:52:12 - Found installed product - Microsoft Visual Studio Professional 2015
28.02.2016 17:52:12 - Found installed product - Microsoft Visual Studio Community 2015
28.02.2016 17:52:12 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
28.02.2016 17:52:12 - Found installed product - Global Location
28.02.2016 17:52:12 - Found installed product - ssms
28.02.2016 17:52:12 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Didn't people already successfully install the plugin into 2015? I found https://social.msdn.microsoft.com/Forums/vstudio/en-US/91c39d64-6d51-41a5-8fc6-bc2bef6394df/this-extension-is-not-installable-on-any-currently-installed-products?forum=vsx but haven't been able to solve the problem. If I explicitly open the vsix with the VS 2015 vsixinstaller.exe I still get the same error message.

**Comment by lothrop** [comment]
Before you go and rebuild I would like to find out if the installer works for anyone else. The problem might be on my end.

**Comment by asudbury** [comment]
I have had no other feedback from anyone regarding installation which is a bit disappointing :-(

I have installed it on 3 machines but they all have vs2013 still installed.

the vsix file is just a zip file and i assumed it just did an xcopy and set up some registry settings to plugin into VS2015.

**Comment by asudbury** [comment]
@lothrop spotted a potential type in the manifest file 

link to version 3.9.4 below download below

https://dl.dropboxusercontent.com/u/3181019/NinjaCoderMvvmCross.vsix.vsix

last attempt to today!

**Comment by lothrop** [comment]
@asudbury Ah, much better!

**Comment by asudbury** [comment]
@lothrop did it actually install :-)

**Comment by lothrop** [comment]
It installed, and i am deeply impressed. The number of possibilities you offer is astounding.

I haven't had much time to test. I tried iOS mostly. The startup project wasn't set to iOS as I had selected (just a minor glitch). I tried using a xib file. You're overwriting the xib's contents in the first line of `ViewDidLoad`. :wink: Actually, the line

`this.View = new UIView { BackgroundColor = UIColor.White };`

shouldn't be necessary for hand-coded iOS either...

After that, everything seemed to work. Good work!

**Comment by asudbury** [comment]
@lothrop we got there in the end :-)

raise bugs on here with details and I will try and fix

thanks for your help - as always.

**Comment by asudbury** [comment]
@lothrop - so just be clear I need to take out the following line in ALL view files (hardcoded, xib and storyboard)

this.View = new UIView { BackgroundColor = UIColor.White };

**Comment by lothrop** [comment]
@asudbury Right.

**Comment by asudbury** [comment]
GitHub t4 templates updated.

You should see changes now if you don't have local config files enabled (by default they are not)

**Comment by lothrop** [comment]
Tiny detail: I picked Storyboard but it created a view with a XIB.

**Comment by asudbury** [comment]
@lothrop - I cant seem to recreate your issue - ill probably need your NinjaReadMe.txt and the logfile to work out what is going in.

**Comment by asudbury** [comment]
@lothrop - any thoughts on what the problem is? 

I want to release as soon as possible - I might need to hold back on Xib and StoryBoard support if not working.

**Comment by asudbury** [comment]
v4.0.0 now released.
