### ISSUE TITLE
Windows Universal sdk version and exception 'object reference not set...'

### ISSUE THREAD

**Issue by pedropete11gmail** [asudbury/NinjaCoderForMvvmCross#227]
NC 4.2.1., WU default TargetPlatformSDK is set to 10.0.10586
Latest SDK is 10.0.14393
During project creation, generates exception, "Object reference not set to an instance of an object", when 14393 is installed (and never installed 10586): 

Workaround; edit installed template file and change SDK version: ...AppData\Local\Microsoft\VisualStudio\14.0\Extensions\z1zktcou.a22\ProjectTemplates\CSharp\Ninja Coder\NinjaCoder.WindowsUniversal.zip

Change: <TargetPlatformVersion>10.0.10586.0</TargetPlatformVersion>
To: <TargetPlatformVersion>10.0.14393.0</TargetPlatformVersion>

Here is an example list of message box contents when the exception is reported:
---------------------------
Ninja Coder for MvvmCross and Xamarin Forms
---------------------------
error adding project exception=The method or operation is not implemented.
---------------------------
OK   
---------------------------

---------------------------
Ninja Coder for MvvmCross and Xamarin Forms
---------------------------
projectPath=S:\NcTest6\NcTest6.WindowsUniversal\
---------------------------
OK   
---------------------------

---------------------------
Ninja Coder for MvvmCross and Xamarin Forms
---------------------------
projectInfo.TemplateName=NinjaCoder.WindowsUniversal.zip
---------------------------
OK   
---------------------------

---------------------------
Ninja Coder for MvvmCross and Xamarin Forms
---------------------------
Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------

---------------------------
Ninja Coder for MvvmCross and Xamarin Forms
---------------------------
   at Scorchio.VisualStudio.Extensions.ProjectExtensions.AddProjectReference(Project instance, Project referencedProject)

   at Scorchio.VisualStudio.Services.ProjectService.AddProjectReference(IProjectService referencedProjectService)

   at NinjaCoder.MvvmCross.Services.ProjectsService.AddProject(String path, ProjectTemplateInfo projectInfo)

   at NinjaCoder.MvvmCross.Services.ProjectsService.AddProjects(IVisualStudioService visualStudioServiceInstance, String path, IEnumerable`1 projectsInfos)

   at NinjaCoder.MvvmCross.Controllers.ProjectsController.Process(ProjectsViewModel projectsViewModel, ApplicationOptionsViewModel applicationOptionsViewModel, NinjaCoderOptionsViewModel ninjaCoderOptionsViewModel, ApplicationSamplesOptionsViewModel applicationSamplesOptionsViewModel, ViewsViewModel viewsViewModel, PluginsViewModel pluginsViewModel, NugetPackagesViewModel nugetPackagesViewModel, XamarinFormsLabsViewModel xamarinFormsLabsViewModel)

   at NinjaCoder.MvvmCross.Controllers.ProjectsController.Run()
---------------------------
OK   
---------------------------

**Comment by asudbury** [comment]
@pedropete11 thanks for the detailed info - will look at fixing as soon as i can.
